services:
  web:
    image: itol_task_manager:prod
    restart: 'always'
    env_file:
      - .env
    volumes:
      - ./db/:/app/db
    expose:
      - '${PORT}'
  caddy:
    image: caddy:2
    env_file:
      - .env
    ports:
      - '${CADDY_PORT}:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src/static:/srv/:ro
    depends_on:
      - web
