services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    expose:
      - '${PORT}'

  caddy:
    image: caddy:2
    env_file:
      - .env
    ports:
      - '${CADDY_PORT}:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src/static:/srv/:ro
    depends_on:
      - web
