[tool.ruff]
line-length = 79
extend-ignore = [
    "F401", "F811", "F821", "F841", "F822", "F722"
]

[tool.ruff.lint.isort]
# Place 'from ... import ...' lines before straight imports
from-first = true
# Force each imported name onto its own line when aliased
force-wrap-aliases = true
# Customize how many blank lines between import sections
lines-between-types = 1

[tool.ruff.lint]
select        = ["E4", "E7", "E9", "F"]
# extend-select = ["W", "C90", "C901", "D", "N", "I","ANN", "TID"]  # e.g. add type and tidy-import rules
fixable       = ["ALL"]         # allow auto-fixing where safe

[tool.pyright]
exclude= [ "**/node_modules", "**/__pycache__"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["-v", "--tb=short", "--strict-markers"]
markers = ["slow: marks tests as slow"]
